// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';

var StringHof$Stringhofutils = require("./StringHof.bs.js");

function addDash(s) {
  return s + "-";
}

var result = StringHof$Stringhofutils.stringMap("abcde", addDash);

console.log(result);

function toCode(s) {
  return s.charCodeAt(0);
}

var result2 = StringHof$Stringhofutils.map("abcde", toCode);

console.log(result2);

function nonVowel(s) {
  return !(s === "a" || s === "e" || s === "i" || s === "o" || s === "u");
}

var result3 = StringHof$Stringhofutils.stringKeep("cauliflower", nonVowel);

console.log(result3);

var result4 = StringHof$Stringhofutils.keep("cauliflower", nonVowel);

console.log(result4);

function reverser(acc, item) {
  return item + acc;
}

var result5 = StringHof$Stringhofutils.reduce("abcde", "", reverser);

console.log(result5);

function addCharCodes(total, s) {
  return total + s.charCodeAt(0);
}

var result6 = StringHof$Stringhofutils.reduce("abc", 0.0, addCharCodes);

console.log(result6);

exports.addDash = addDash;
exports.result = result;
exports.toCode = toCode;
exports.result2 = result2;
exports.nonVowel = nonVowel;
exports.result3 = result3;
exports.result4 = result4;
exports.reverser = reverser;
exports.result5 = result5;
exports.addCharCodes = addCharCodes;
exports.result6 = result6;
/* result Not a pure module */
